### ISSUE TITLE
gigabytes

### ISSUE THREAD

**Issue by valireality** [Darkseal/RunningLow#1]
Hi, your script is excellent.
But please can you tell how to report in GB?

Thank you.

**Comment by Darkseal** [comment]
Hello there,

the byte-to-GB conversion has already been implemented in the code (between parenthesis, after the byte count). 

As a general rule, wherever you see this:

    $disk.Free + " bytes"

You can also do this instead:

    ($disk.Free/1GB).ToString(".00") + " GB"

That's it.
